using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MarketDataFinance.Application.ViewModels
{
    public class QuoteViewModel(string MarketState, string Exchange, double FiftyTwoWeekHighChange, string CustomPriceAlertConfidence, int AverageDailyVolume10Day, string ShortName, bool Triggerable, double AnnualReturnNavY3, object FirstTradeDateMilliseconds, string Language, int ExchangeDataDelayedBy, bool CryptoTradeable, string ExchangeTimezoneShortName, string ExchangeTimezoneName, double TwoHundredDayAverage, double RegularMarketChange, double RegularMarketOpen, int BidSize, double Bid, double TwoHundredDayAverageChangePercent, double RegularMarketDayHigh, double Ask, double NetExpenseRatio, int RegularMarketTime, double FiftyTwoWeekLow, bool HasPrePostMarketData, string MessageBoardId, string LongName, double TrailingThreeMonthReturns, double AnnualReturnNavY5, double RegularMarketPrice, string QuoteSourceName, double RegularMarketChangePercent, double RegularMarketDayLow, bool Tradeable, string FullExchangeName, double RegularMarketPreviousClose, string Symbol, int RegularMarketVolume, double YtdReturn, string Market, double FiftyDayAverage, string Currency, double FiftyDayAverageChangePercent, double FiftyTwoWeekChangePercent, double FiftyDayAverageChange, int GmtOffSetMilliseconds, double DividendYield, int PriceHint, int AskSize, string TypeDisp, int AverageDailyVolume3Month, string QuoteType, string RegularMarketDayRange, double FiftyTwoWeekHighChangePercent, double FiftyTwoWeekLowChange, int SourceInterval, double FiftyTwoWeekLowChangePercent, string Region, string FiftyTwoWeekRange, CorporateActionsViewModel CorporateActions, double TrailingThreeMonthNavReturns, double TwoHundredDayAverageChange, double FiftyTwoWeekHigh, long NetAssets, bool EsgPopulated, int TrailingAnnualDividendYield, int TrailingAnnualDividendRate, int DividendDate, double EpsTrailingTwelveMonths, double TrailingPE, double YieldTTM, double PeTTM, string DisplayName, int EarningsTimestampStart, int EarningsTimestamp, int EarningsTimestampEnd, int EarningsCallTimestampStart, int EarningsCallTimestampEnd, bool IsEarningsDateEstimate);
}
