name: Publish to network share

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Map network drive
        run: |
          net use Q: \\10.228.2.91\c\barramento\Prod\Barramento_MarketDataFinance /user:treviso\wesley.bezerra ZN!LXp@W5K

      - name: Publish
        run: dotnet publish "C:\Users\wesley.bezerra\OneDrive - TREVISO\Treviso\Treviso\MarketDataFinance\MarketDataFinance\MarketDataFinance.csproj" --configuration Release --output Q:\
